
copyright: Fincz
title: "How to Start Investing in Stocks"
description : "Best Blog For Business and Investment Tips for Share market, Online Earning, Loans, Credit Cards, Insurance Etc."
email: fincz.it@gmail.com
timezone: IST
siteurl: 'https://fincz.com'
baseurl: ''
lazy_img: 'assets/images/fincz-lazy.png'
permalink: "/:title/"
logo: 'assets/images/fincz-logo-black.png'
favicon: 'assets/images/apple-icon-black.png'
author: Ahmad
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-SP0MLCNXK8
# Authors
authors:
  Ahmad:
    name: Ahmad
    display_name: Ahmad
    avatar: 'assets/images/ahmad.png'
    email: itechf@hotmail.com
    web: https://itechf.com
    twitter: https://twitter.com/itechf2
    description: "Author of FinCz a website for share market"
  Nazir:
    name: Nazir
    display_name: Nazir
    avatar: 'assets/images/nazir.png'
    email: nazir@theislah.com
    web: https://bestrani.com
    twitter: https://twitter.com/bestrani3
    description: "Nazir has so much experience of content writing"

# Social
social:
#  instagram: https://www.instagram.com/fincz/
  facebook: https://www.facebook.com/Share-Market-123554999895949
  twitter: https://twitter.com/fincz1

seo:
  image: /assets/images/fincz-default-image.png
  image-type: image/jpeg
  image-width: 1200
  image-height: 680
  locale: en_US
  locale-alternate: en_IN
  twitter-site: '@Itechf1'
  datePublished: 2021-07-31T08:00:00+530

pwa:
  enabled: true # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional



# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-minifier